### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by czechnology**
### Proposed changes

Current logging approach in the library does not follow best practices.
* > It is strongly advised that you do not log to the root logger in your library. Instead, use a logger with a unique and easily identifiable name, such as the __name__ for your library’s top-level package or module. Logging to the root logger will make it difficult or impossible for the application developer to configure the logging verbosity or handlers of your library as they wish. [[ref]][1]
* > Formatting of message arguments is deferred until it cannot be avoided. However, computing the arguments passed to the logging method can also be expensive, and you may want to avoid doing it if the logger will just throw away your event. [[ref]][2]
* Using custom methods for what is already provided by the logging library.

[1]: https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
[2]: https://docs.python.org/3/howto/logging.html#optimization

This change refactors logging in the whole library to follow best practices and common approach (to the best of my knowledge).
* Instead of logging to the root logger (`logging.info(...)` etc.), introduce more specific loggers, namely `pycti.api`, `pycti.connector`, and `pycti.entities` (following the higher-level modules in the library), along with a `tests` logger for the logs.
* Use the standard logger.{debug|info|error} methods, instead of unnecessary wrappers.
* Use the `%` string formatting, which is used by the logging library. This avoids unnecessary string computation in case the logging level is higher than the logging call.
* Check the logging level where expensive computation (such as `json.dumps`) might occur unnecessarily).

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

I tried not to modify existing functionality, my aim was to improve the logging strategy without breaking anything.
However, I would argue that some of the logging configuration does not really belong in a library code, or at least should not be called by default, and let the users of the library configure the logging according to their needs. But for the sake of not breaking anything, I have not modified that behavior. This change should at least provide users the possibility to configure the logging levels of this library by avoiding the root logger.

Thanks in advance for your help reviewing this long PR!

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello @czechnology,

Thanks a lot for your PR! Can you please fix the conflicts and we will merge it just after?

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Hello @czechnology,

Any news from the conflict resolution?

**Comment by czechnology** [comment]
Sorry, holidays got in the way, might take a while longer to get on this, sorry!

**Comment by SamuelHassine** [comment]
No problem @czechnology it was just to know if you was still working on this. Thanks a lot for this great contribution and happy new year!

**Comment by czechnology** [comment]
Hi, Samuel, rebased now. Happy new year to you as well! :)

**Review by SamuelHassine — APPROVED** [review]

**Pull request merged**
