### PR TITLE
Add basic pytest framework

### PR DESCRIPTION
**Pull request by rhaist**
This is a Draft PR to show how pytest could be integrated into the code base and CI/CD.

* It adds coverage for most code paths of the Indicator class
* It changes the circle-ci to Python 3.9 for all instances
* It bumps dependencies
* It fixes the existing test by @richard-julien 
* It adds a new test token for the current demo instance of OpenCTI
* It fixes the sphinx documentation for some classes (more TODOs are open on that front)

### CODE REVIEW

**Comment by rhaist** [comment]
Example output for test run:
```
λ python3 -m pytest --cov=pycti
=================================================================== test session starts ====================================================================
platform darwin -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/foo/git/client-python, inifile: pytest.ini
plugins: cov-2.8.1
collected 6 items

tests/test_indicators.py ......                                                                                                                      [100%]

---------- coverage: platform darwin, python 3.8.2-final-0 -----------
Name                                                 Stmts   Miss  Cover
------------------------------------------------------------------------
pycti/__init__.py                                       34      0   100%
pycti/api/__init__.py                                    0      0   100%
pycti/api/opencti_api_client.py                        296    100    66%
pycti/api/opencti_api_connector.py                      20     10    50%
pycti/api/opencti_api_job.py                            15      8    47%
pycti/connector/__init__.py                              0      0   100%
pycti/connector/opencti_connector.py                    16      7    56%
pycti/connector/opencti_connector_helper.py            263    218    17%
pycti/entities/__init__.py                               0      0   100%
pycti/entities/opencti_attack_pattern.py               166    153     8%
pycti/entities/opencti_campaign.py                     132     85    36%
pycti/entities/opencti_course_of_action.py             111     99    11%
pycti/entities/opencti_external_reference.py            62     53    15%
pycti/entities/opencti_identity.py                     123     94    24%
pycti/entities/opencti_incident.py                     150    137     9%
pycti/entities/opencti_indicator.py                    185     66    64%
pycti/entities/opencti_intrusion_set.py                160    148     8%
pycti/entities/opencti_kill_chain_phase.py              60     51    15%
pycti/entities/opencti_malware.py                      119    107    10%
pycti/entities/opencti_marking_definition.py            65     56    14%
pycti/entities/opencti_note.py                         199    181     9%
pycti/entities/opencti_opinion.py                      191    173     9%
pycti/entities/opencti_report.py                       204    185     9%
pycti/entities/opencti_stix_domain_entity.py           115     64    44%
pycti/entities/opencti_stix_entity.py                  140    119    15%
pycti/entities/opencti_stix_observable.py              131     80    39%
pycti/entities/opencti_stix_observable_relation.py     150    139     7%
pycti/entities/opencti_stix_relation.py                224    152    32%
pycti/entities/opencti_stix_sighting.py                183    168     8%
pycti/entities/opencti_tag.py                           53     44    17%
pycti/entities/opencti_threat_actor.py                 164    139    15%
pycti/entities/opencti_tool.py                         113    101    11%
pycti/entities/opencti_vulnerability.py                146    134     8%
pycti/utils/__init__.py                                  0      0   100%
pycti/utils/constants.py                                90      2    98%
pycti/utils/opencti_stix2.py                           809    655    19%
------------------------------------------------------------------------
TOTAL                                                 4889   3728    24%
```

**Comment by SamuelHassine** [comment]
@rhaist: Thanks a lot for this good work to bootstrap testing suit over the Python library. We would like to push hard on this. Can you please solve conflicts on this PR so we can merge and continue the work?

Thanks!

**Comment by rhaist** [comment]
I'll get on it ASAP 🤟

**Comment by rhaist** [comment]
I just edited by initial PR message on the top to reflect all changes in this PR.
@SamuelHassine or @richard-julien -> Ready to merge from my side.

**Comment by SamuelHassine** [comment]
Thanks a lot @rhaist. I will merge this and add these first tests to our CI, using also codecov.

**Pull request merged**
